import os
import re
from datetime import datetime
from fpdf import FPDF
from crewai.tools import BaseTool
from pydantic import BaseModel, Field
from typing import Type, Optional
import logging
import unicodedata

logger = logging.getLogger(__name__)

class PDFGeneratorInput(BaseModel):
    """Input for PDFGeneratorTool."""
    content: str = Field(..., description="The main content/post to be saved as PDF.")
    topic: str = Field(..., description="The topic of the post.")
    strategy_summary: Optional[str] = Field(None, description="Optional summary of keywords and posting strategy.")

class PDFGeneratorTool(BaseTool):
    name: str = "pdf_generator_tool"
    description: str = "Generates a professional PDF document containing the LinkedIn post and strategy."
    args_schema: Type[BaseModel] = PDFGeneratorInput
    
    def _clean_text(self, text: str) -> str:
        """Thoroughly clean text for Latin-1 PDF compatibility."""
        if not text:
            return ""
        
        # 1. Hard-coded common problematic character mappings
        replacements = {
            '\u2013': '-', # en dash
            '\u2014': '--', # em dash
            '\u2018': "'", # left single quote
            '\u2019': "'", # right single quote
            '\u201c': '"', # left double quote
            '\u201d': '"', # right double quote
            '\u2022': '*', # bullet
            '\u2026': '...', # ellipsis
            '\u2122': '(TM)',
            '\u00ae': '(R)',
            '\u00a9': '(C)',
            '\u20ac': 'EUR',
            '—': '--',
            '–': '-',
            '‘': "'",
            '’': "'",
            '“': '"',
            '”': '"',
            '…': '...',
            '’': "'", # redundant check for different encodings
        }
        
        for char, replacement in replacements.items():
            text = text.replace(char, replacement)
            
        # 2. Normalize Unicode (decomposes combined characters like accents)
        text = unicodedata.normalize('NFKD', text)
        
        # 3. Final safety: encode to latin-1 and ignore anything that can't be translated
        # Use 'ignore' or 'replace' but 'replace' gives '?' which we want to avoid for known chars
        return text.encode('latin-1', 'replace').decode('latin-1')

    def _run(self, content: str, topic: str, strategy_summary: Optional[str] = None) -> str:
        logger.info(f"PDFGeneratorTool: Generating professional PDF for: {topic}")
        
        output_dir = "storage/pdfs"
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)
            
        date_str = datetime.now().strftime("%Y-%m-%d")
        safe_topic = re.sub(r'[^\w\-]', '', re.sub(r'[\s]+', '-', topic.strip()))
        filename = f"{date_str}-{safe_topic}.pdf"
        filepath = os.path.join(output_dir, filename)
        
        class ProfessionalPDF(FPDF):
            def header(self):
                self.set_font("helvetica", "B", 8)
                self.set_text_color(150, 150, 150)
                self.cell(0, 10, f"LinkedIn Content Strategy | {datetime.now().strftime('%B %Y')}", border=0, ln=1, align="R")
                self.ln(5)

            def footer(self):
                self.set_y(-15)
                self.set_font("helvetica", "I", 8)
                self.set_text_color(150, 150, 150)
                self.cell(0, 10, f"Page {self.page_no()} | Generated by AI Agentic Workflow", 0, 0, "C")

        pdf = ProfessionalPDF()
        pdf.add_page()
        
        # Set auto page break
        pdf.set_auto_page_break(auto=True, margin=15)
        
        # Title Section
        pdf.set_font("helvetica", "B", 24)
        pdf.set_text_color(31, 73, 125) # Navy Blue
        title_text = self._clean_text(f"Content Blueprint: {topic}")
        pdf.multi_cell(0, 15, title_text)
        pdf.ln(5)
        
        pdf.set_draw_color(31, 73, 125)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(10)
        
        # Strategy Section (if available)
        if strategy_summary:
            pdf.set_font("helvetica", "B", 14)
            pdf.set_text_color(0, 0, 0)
            pdf.cell(0, 10, "1. Strategic Overview", ln=True)
            pdf.set_font("helvetica", "", 11)
            pdf.set_text_color(80, 80, 80)
            
            clean_strategy = self._clean_text(strategy_summary)
            pdf.multi_cell(0, 7, clean_strategy)
            pdf.ln(10)
        
        # Post Section
        pdf.set_font("helvetica", "B", 14)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, "2. Optimized LinkedIn Post", ln=True)
        pdf.ln(2)
        
        # Post Box
        pdf.set_fill_color(245, 247, 249)
        pdf.set_font("helvetica", "", 12)
        pdf.set_text_color(0, 0, 0)
        
        clean_content = self._clean_text(content)
        pdf.multi_cell(0, 8, clean_content, border=0, fill=True)
        
        pdf.output(filepath)
        
        return f"Professional PDF generated successfully at: {filepath}"
